site_name: Pi4U
pages:
  - Home: index.md
  - Installation: installation.md
  - Examples: examples.md
  - Developing: developing.md
  - Postprocessing: post.md
  - Performance and Scalability: hpc.md
theme: readthedocs
